// src/logic/wasm-init/NavConst.ts

export const NavConst = {
    STUCK_PASSIVE_X1: 14,
    STUCK_DST_X2: 18,
    STUCK_CORRIDOR_X3: 40,
    STUCK_DECAY: 0.8,
    STUCK_DANGER_1: 35,
    STUCK_DANGER_2: 45,
    STUCK_DANGER_3: 75,
    STUCK_HIT_WALL: 10,
    PATH_LOG_RATE: 3,
    LOOK_ROT_SPEED_RAD_S: 6.0,
    CORRIDOR_EXPECTED_JUMP: 120,

    ARRIVAL_THRESHOLD_SQ_DEFAULT: 4,
    ARRIVAL_DESIRED_SPEED_DEFAULT: 1,
    MAX_SPEED_DEFAULT: 3,
    ACCEL_DEFAULT: 20,
    RESISTANCE_DEFAULT: 0.1,
    MAX_FRUSTRATION_DEFAULT: 10,

    CORNER_OFFSET: 2.1,
    CORNER_OFFSET_SQ: 2.1 * 2.1,
}; 