#ifndef CONSTANTS_LAYOUT_H
#define CONSTANTS_LAYOUT_H

#include <cstdint>

extern uint8_t* g_constants_buffer; // defined in main.cpp

#define CONST_F32_AT(OFFSET) (*reinterpret_cast<float*>(g_constants_buffer + (OFFSET)))
#define CONST_I32_AT(OFFSET) (*reinterpret_cast<int32_t*>(g_constants_buffer + (OFFSET)))

// Offsets MUST match src/logic/wasm/ConstantsLayout.ts
#define OFFSET_STUCK_PASSIVE_X1 0
#define OFFSET_STUCK_DST_X2 4
#define OFFSET_STUCK_CORRIDOR_X3 8
#define OFFSET_STUCK_DECAY 12
#define OFFSET_STUCK_DANGER_1 16
#define OFFSET_STUCK_DANGER_2 20
#define OFFSET_STUCK_DANGER_3 24
#define OFFSET_STUCK_HIT_WALL 28
#define OFFSET_PATH_LOG_RATE 32
// Note: LOOK_ROT_SPEED_RAD_S was previously at offset 32 in TS, but PATH_LOG_RATE is an int, so alignment is correct.
#define OFFSET_LOOK_ROT_SPEED_RAD_S 36 
#define OFFSET_CORRIDOR_EXPECTED_JUMP 40
#define OFFSET_ARRIVAL_THRESHOLD_SQ_DEFAULT 44
#define OFFSET_ARRIVAL_DESIRED_SPEED_DEFAULT 48
#define OFFSET_MAX_SPEED_DEFAULT 52
#define OFFSET_ACCEL_DEFAULT 56
#define OFFSET_RESISTANCE_DEFAULT 60
#define OFFSET_MAX_FRUSTRATION_DEFAULT 64
#define OFFSET_CORNER_OFFSET 68
#define OFFSET_CORNER_OFFSET_SQ 72

// Named macros for convenience
// All floats except PATH_LOG_RATE
#define STUCK_PASSIVE_X1 CONST_F32_AT(OFFSET_STUCK_PASSIVE_X1)
#define STUCK_DST_X2 CONST_F32_AT(OFFSET_STUCK_DST_X2)
#define STUCK_CORRIDOR_X3 CONST_F32_AT(OFFSET_STUCK_CORRIDOR_X3)
#define STUCK_DECAY CONST_F32_AT(OFFSET_STUCK_DECAY)
#define STUCK_DANGER_1 CONST_F32_AT(OFFSET_STUCK_DANGER_1)
#define STUCK_DANGER_2 CONST_F32_AT(OFFSET_STUCK_DANGER_2)
#define STUCK_DANGER_3 CONST_F32_AT(OFFSET_STUCK_DANGER_3)
#define STUCK_HIT_WALL CONST_F32_AT(OFFSET_STUCK_HIT_WALL)
#define PATH_LOG_RATE CONST_I32_AT(OFFSET_PATH_LOG_RATE)
#define CORNER_OFFSET CONST_F32_AT(OFFSET_CORNER_OFFSET)
#define CORNER_OFFSET_SQ CONST_F32_AT(OFFSET_CORNER_OFFSET_SQ)
#define LOOK_ROT_SPEED_RAD_S CONST_F32_AT(OFFSET_LOOK_ROT_SPEED_RAD_S)
#define CORRIDOR_EXPECTED_JUMP CONST_F32_AT(OFFSET_CORRIDOR_EXPECTED_JUMP)
#define ARRIVAL_THRESHOLD_SQ_DEFAULT CONST_F32_AT(OFFSET_ARRIVAL_THRESHOLD_SQ_DEFAULT)
#define ARRIVAL_DESIRED_SPEED_DEFAULT CONST_F32_AT(OFFSET_ARRIVAL_DESIRED_SPEED_DEFAULT)
#define MAX_SPEED_DEFAULT CONST_F32_AT(OFFSET_MAX_SPEED_DEFAULT)
#define ACCEL_DEFAULT CONST_F32_AT(OFFSET_ACCEL_DEFAULT)
#define RESISTANCE_DEFAULT CONST_F32_AT(OFFSET_RESISTANCE_DEFAULT)
#define MAX_FRUSTRATION_DEFAULT CONST_F32_AT(OFFSET_MAX_FRUSTRATION_DEFAULT)

#endif // CONSTANTS_LAYOUT_H