#ifndef CONSTANTS_LAYOUT_H
#define CONSTANTS_LAYOUT_H

#include <cstdint>

extern uint8_t* g_constants_buffer; // defined in main.cpp

#define CONST_F32_AT(OFFSET) (*reinterpret_cast<float*>(g_constants_buffer + (OFFSET)))
#define CONST_I32_AT(OFFSET) (*reinterpret_cast<int32_t*>(g_constants_buffer + (OFFSET)))

// Offsets MUST match src/logic/wasm/ConstantsLayout.ts
#define OFFSET_STUCK_PASSIVE_X1 0
#define OFFSET_STUCK_DST_X2 4
#define OFFSET_STUCK_CORRIDOR_X3 8
#define OFFSET_STUCK_DECAY 12
#define OFFSET_STUCK_DANGER_1 16
#define OFFSET_STUCK_DANGER_2 20
#define OFFSET_STUCK_DANGER_3 24
#define OFFSET_PATH_LOG_RATE 28
#define OFFSET_CORNER_OFFSET 32
#define OFFSET_CORNER_OFFSET_SQ 36
#define OFFSET_LOOK_ROT_SPEED_RAD_S 40

// Named macros for convenience
// All floats except PATH_LOG_RATE
#define STUCK_PASSIVE_X1 CONST_F32_AT(OFFSET_STUCK_PASSIVE_X1)
#define STUCK_DST_X2 CONST_F32_AT(OFFSET_STUCK_DST_X2)
#define STUCK_CORRIDOR_X3 CONST_F32_AT(OFFSET_STUCK_CORRIDOR_X3)
#define STUCK_DECAY CONST_F32_AT(OFFSET_STUCK_DECAY)
#define STUCK_DANGER_1 CONST_F32_AT(OFFSET_STUCK_DANGER_1)
#define STUCK_DANGER_2 CONST_F32_AT(OFFSET_STUCK_DANGER_2)
#define STUCK_DANGER_3 CONST_F32_AT(OFFSET_STUCK_DANGER_3)
#define PATH_LOG_RATE CONST_I32_AT(OFFSET_PATH_LOG_RATE)
#define CORNER_OFFSET CONST_F32_AT(OFFSET_CORNER_OFFSET)
#define CORNER_OFFSET_SQ CONST_F32_AT(OFFSET_CORNER_OFFSET_SQ)
#define LOOK_ROT_SPEED_RAD_S CONST_F32_AT(OFFSET_LOOK_ROT_SPEED_RAD_S)

#endif // CONSTANTS_LAYOUT_H 